### ISSUE TITLE
Add Jenkinsfile

### ISSUE THREAD

**Issue by josephworks** [Paul1365972/Ilblu#2]
I would like to build this on my Jenkins server, but it doesn't have a Jenkinsfile, so I can't use BlueOcean.
Here is a sample Jenkinsfile that I use in one of my projects:
```groovy
pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'bash ./gradlew build'
      }
    }

    stage('ProcessMod') {
      steps {
        sh 'mv build/libs/modid-1.0.jar build/libs/JosephCore.jar'
      }
    }

    stage('Archive') {
      steps {
        archiveArtifacts(artifacts: 'build/libs/*', fingerprint: true)
      }
    }

  }
}
```

**Comment by Paul1365972** [comment]
I am not really sure why you would want to build this project with jenkins, as this repository is just a template with no actual functionality and only meant to be forked. If you want to build your own fork you could always just add the Jenkinsfile in your own repository only, or did I miss something?

**Comment by josephworks** [comment]
I suppose, but it would be nice to provide the Jenkinsfile so others can (extremely) easily build our forks of the project on Jenkins.

**Comment by Paul1365972** [comment]
Since I don't want to clutter the project with build system files I will just provide this simple pipeline script. Be warned i have no experience with the Jenkins pipeline, but it worked fine in my test runs. Just replace <USER-NAME> and <FORK-NAME> and you should be good to go.

```groovy
pipeline {
   agent any
   
   stages {
      stage('Setup') {
          steps {
            git 'https://github.com/<USER-NAME>/<FORK-NAME>.git'
            
            sh './gradlew ilbluInitApply'
          }
      }
      stage('Build') {
         steps {
            sh './gradlew jar sourcesJar javadocJar shadowJar ilbluPaperclip'
            
            archiveArtifacts 'ilblu-paperclip.jar, <FORK-NAME>-API/build/libs/*.jar'
         }
      }
   }
}
```
